let livres =  // Tableau de livres
[
  {
    idLivre: 1,
    titre: "Anna Karenine",
    extrait: "https://beq.ebooksgratuits.com/vents/Tolstoi-Karenine-1.pdf",
    resume: "Le drame de ladultere dAnna Karenine, qui entraine des consequences tragiques dans la haute societe russe.",
    anneeEdition: 1877,
    imageCouverture: "https://cdn.cultura.com/cdn-cgi/image/width=830/media/pim/TITELIVE/14_9782755648041_1_75.jpg",
    id_categorie: 1,
    nbPage : 250,
    idAuteur: 1,
  },
  {
    idLivre: 2,
    titre: "Le Proces",
    extrait: "http://data0.eklablog.com/ae-editions/perso/bibliotheque%20-%20pdf/kafka%20-%20le%20proces.pdf",
    resume: "Joseph K. est accuse dun crime mysterieux et se retrouve pris dans un systeme judiciaire kafkaïen.",
    anneeEdition: 1925,
    imageCouverture: "../src/assets/LeProces.jpg",
    id_categorie: 2,
    nbPage : 257,
    idAuteur: 2,
  },
  {
    idLivre: 3,
    titre: "Don Quichotte",
    extrait: "https://beq.ebooksgratuits.com/cervantes/Cervantes-1.pdf",
    resume: "Les aventures de Don Quichotte et de son fidele ecuyer Sancho Panza, qui parcourent lEspagne en quete didealisme.",
    anneeEdition: 1605,
    imageCouverture: "../src/assets/DonQuichotte.jpg",
    id_categorie: 3,
    nbPage : 280,
    idAuteur: 3,
  },
  {
    idLivre: 4,
    titre: "Le Comte de Monte-Cristo",
    extrait: "https://beq.ebooksgratuits.com/vents/Dumas_Le_comte_de_Monte_Cristo_1.pdf",
    resume: "Edmond Dantes cherche vengeance apres avoir ete trahi et emprisonne a tort.",
    anneeEdition: 1844,
    imageCouverture: "../src/assets/Monte-Cristo.jpg",
    id_categorie: 5,
    nbPage : 504,
    idAuteur: 4,
  },
  {
    idLivre: 5,
    titre: "Les Freres Karamazov",
    extrait: "https://www.beq.ebooksgratuits.com/vents-xpdf/Dostoievski-Karamazov-1.pdf",
    resume: "Les relations tumultueuses entre les freres Karamazov, qui sont temoins de la mort de leur pere.",
    anneeEdition: 1880,
    imageCouverture: "../src/assets/Karamazov.jpg",
    id_categorie: 5,
    nbPage : 440,
    idAuteur: 5,
  }
]

export { livres };