version: "3"
 
services:
  db:
    image: mysql:latest
    container_name: mysql 
    environment: 
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_USER: db_user 
      MYSQL_PASSWORD: db_user_pass 
    restart: always 
    ports: 
      - "3306:3306"
    expose: 
      - 3306
  php: 
    image: phpmyadmin/phpmyadmin
    container_name: php
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - "8080:80"